name: Build Yocto

on:
  workflow_call:
    inputs:
      use_sstate:
        description: "Use SSTATE cache"
        required: false
        default: "true"
        type: string
    outputs:
      artifacts_url:
        description: "URL to retrieve build artifacts"
        value: ${{ jobs.create-output.outputs.url }}

# Concurrency is used to prevent multiple workflows from running for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || format('push-{0}', github.sha) }}
  cancel-in-progress: true

env:
  CACHE_DIR: /efsx/qli/meta-qcom-robotics-sdk
  KAS_CLONE_DEPTH: 1

jobs:
  kas-setup:
    if: github.repository_owner == 'qualcomm-linux'    
    runs-on: [self-hosted, qcom-u2404, amd64]
    steps:
      - name: Setting up kas-container
        run: |
          KAS_CONTAINER=$RUNNER_TEMP/kas-container
          echo "KAS_CONTAINER=$KAS_CONTAINER" >> $GITHUB_ENV
          LATEST=$(git ls-remote --tags --refs --sort="v:refname" https://github.com/siemens/kas | tail -n1 | sed 's/.*\///')
          wget -qO ${KAS_CONTAINER} https://raw.githubusercontent.com/siemens/kas/refs/tags/$LATEST/kas-container
          chmod +x ${KAS_CONTAINER}

      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run kas lock
        run: |
          ${KAS_CONTAINER} lock --update ci/qcom-robotics-distro.yml

      - name: Upload kas lockfile
        uses: actions/upload-artifact@v6
        with:
          name: kas-lockfile
          path: ci/*.lock.yml

      - name: Upload kas-container
        uses: actions/upload-artifact@v6
        with:
          name: kas-container
          path: ${{ env.KAS_CONTAINER }}

  yocto-run-checks:
    needs: kas-setup
    
    runs-on: [self-hosted, qcom-u2404, amd64]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      # qcom-robotics-distro.yml used special commit id, so we need to fetch it again
      # - name: Download kas lockfile
      #   uses: actions/download-artifact@v6
      #   with:
      #     name: kas-lockfile
      #     path: ci

      - name: Download kas-container
        uses: actions/download-artifact@v7
        with:
          name: kas-container
          path: ${{ runner.temp }}

      - name: Setting up kas-container
        run: |
          KAS_CONTAINER=$RUNNER_TEMP/kas-container
          echo "KAS_CONTAINER=$KAS_CONTAINER" >> $GITHUB_ENV
          chmod +x $KAS_CONTAINER

      - name: Run yocto-check-layer
        run: |
          ci/kas-container-shell-helper.sh ci/yocto-check-layer.sh

      - name: Run Yocto patchreview
        run: |
          ci/kas-container-shell-helper.sh ci/yocto-patchreview.sh

  compile:
    needs: [kas-setup, yocto-run-checks]
    if: github.repository_owner == 'qualcomm-linux'    
    runs-on: [self-hosted, qcom-u2404, amd64]
    outputs:
      url: ${{ steps.compile_kas.outputs.url }}
    timeout-minutes: 720 # 12 hours
    strategy:
      fail-fast: true
      matrix:
        machine:
          - iq-8275-evk
          - iq-9075-evk
        distro:
          - name: qcom-robotics-distro
            yamlfile: ':ci/qcom-robotics-distro.yml'
          - name: qcom-robotics-distro-catchall
            yamlfile: ':ci/qcom-robotics-distro-catchall.yml'
          - name: debug
            yamlfile: ':ci/qcom-robotics-distro-catchall.yml:ci/debug.yml'
          - name: performance
            yamlfile: ':ci/qcom-robotics-distro-catchall.yml:ci/performance.yml'
        target:
          - type: '_base'
            name: qcom-robotics-image
            yamlfile: ':ci/qcom-robotics-image.yml'
          - type: '_full'
            name: qcom-robotics-proprietary-image
            yamlfile: ':ci/qcom-robotics-proprietary-image.yml'
        kernel:
          - type: default
            dirname: '_linux-qcom-next'
            yamlfile: ''

    name: ${{ matrix.machine }}/${{ matrix.distro.name }}${{ matrix.target.type }}${{ matrix.kernel.dirname }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run kas build
        uses: ./.github/actions/compile
        id: compile_kas
        with:
          machine: ${{matrix.machine}}
          distro_yaml: ${{matrix.distro.yamlfile}}
          distro_name: ${{matrix.distro.name}}
          target_type: ${{matrix.target.type}}
          target_yaml: ${{matrix.target.yamlfile}}
          target_name: ${{matrix.target.name}}
          kernel_yaml: ${{matrix.kernel.yamlfile}}
          kernel_dirname: ${{matrix.kernel.dirname}}
          cache_dir: ${CACHE_DIR}
          use_sstate: ${{ inputs.use_sstate || 'true' }}

  publish_summary:
    needs: compile
    runs-on: [self-hosted, qcom-u2404, amd64]
    steps:
      - name: 'Download build URLs'
        uses: actions/download-artifact@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: build-url*
          path: urlfiles
          merge-multiple: true

      - name: "Print output"
        shell: python
        id: print-output
        run: |
          import os
          ftable = {}
          oslist = set()
          machinelist = set()
          for fname in os.listdir("./urlfiles"):
              if fname.startswith("build-url"):
                  b, m, o = fname.split("_", 2)
                  oslist.add(o)
                  machinelist.add(m)
                  url = ""
                  with open(f"./urlfiles/{fname}", "r") as urlfile:
                      url = urlfile.read()
                  if not o in ftable:
                      ftable.update({o:{m: url}})
                  else:
                      ftable[o].update({m: url})

          table_str = "| |"

          for m in sorted(machinelist):
              table_str += f" {m} |"

          table_str += "\n|"
          for i in range(len(machinelist) + 1):
              table_str += " ---- |"

          table_str += "\n"

          for o in sorted(ftable.keys()):
              table_str += f"| {o} |"
              for m in sorted(machinelist):
                  url = ftable[o].get(m)
                  if url:
                      url = url.strip()
                      table_str += f" [Files]({url}/{o}/{m}/) |"
                  else:
                      table_str += " |"
              table_str += "\n"
          summary_file_name = os.environ.get("GITHUB_STEP_SUMMARY")
          if summary_file_name:
              with open(summary_file_name, "a") as summaryfile:
                  summaryfile.write("## Download URLs\n")
                  summaryfile.write(table_str)
          print(table_str)