name: Monthly job

on:
  schedule:
  - cron: "22 10 5 * *"   # montly job - at "random" time - top of hour can be busy in github

env:
  CACHE_DIR: /efsx/qli/meta-qcom-robotics-sdk

jobs:
  sstate-cache-cleanup:
    if: github.repository_owner == 'qualcomm-linux'
    runs-on: [self-hosted, qcom-u2404, amd64] 
    timeout-minutes: 720
    steps:
      - name: Clean up the persistant sstate-cache dir
        run: |
          rm -rf $(find "${CACHE_DIR}" -name 'sstate-cache-*' -maxdepth 1 -type d -ctime +30)
